# Generated by Django 4.1.7 on 2023-02-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(default="media/me_hood.jpg", upload_to="media/"),
        ),
    ]
